name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # Kita kunci semua perintah agar berjalan di dalam folder android-app
    defaults:
      run:
        working-directory: ./android-app

    steps:
      - uses: actions/checkout@v4

      # Android butuh Java untuk bisa di-build
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Inject API Key
        run: sed -i 's/INSERT_API_KEY_HERE/${{ secrets.GEMINI_API_KEY }}/g' $GITHUB_WORKSPACE/index.html

      - name: Prepare Android Assets
        run: |
          mkdir -p app/src/main/assets/
          cp $GITHUB_WORKSPACE/index.html app/src/main/assets/index.html

      - name: Grant Permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew :app:assembleDebug --stacktrace
        env:
          GEMINI_API_KEY: ${{ secrets.MODEL_CHANGER }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ChatBotGemini
          # Path harus mengarah dari root repositori
          path: android-app/app/build/outputs/apk/debug/ChatBotGemini.apk
